#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0


runApplication surfaceFeatureExtract
runApplication blockMesh

runApplication decomposePar #-allRegions
mpiexec -n 4 snappyHexMesh -parallel -dict system/snappyHexMeshDict_scaled

reconstructParMesh -latestTime -mergeTol 1E-06

cp 0.org/* 0/
cp 0.org/* 3/

# rm -rf processor*

runApplication 


#runApplication decomposePar -fileHandler collated
#runParallel snappyHexMesh -overwrite -fileHandler collated
# Remove any include files from the field dictionaries
# (   mkdir -p processors/0 && \
#    cd 0 && \
#    for f in *; do [ -f "$f" ] && \
#    foamDictionary "$f" > "../processors/0/$f"; done \
# )


#mpiexec -n 4 $(getApplication) -parallel 

#runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
