#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#mkdir 0


runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar
mpiexec -np 16 -oversubscribe snappyHexMesh -parallel -overwrite 
runApplication reconstructParMesh -constant
runApplication checkMesh -allGeometry -allTopology
# runApplication changeDictionDict
# runApplication setFields
rm -rf processor*
mv log.decomposePar log.decomposePar1
runApplication decomposePar
mpiexec -oversubscribe -np 16 simpleFoam -parallel
runApplication reconstructPar -newTimes
touch c.foam

#runApplication decomposePar -fileHandler collated
#runParallel snappyHexMesh -overwrite -fileHandler collated
# Remove any include files from the field dictionaries
# (   mkdir -p processors/0 && \
#    cd 0 && \
#    for f in *; do [ -f "$f" ] && \
#    foamDictionary "$f" > "../processors/0/$f"; done \
# )


#mpiexec -n 4 $(getApplication) -parallel 

#runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
